/**
 * Exchange rates portal API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExchangeRate } from './exchangeRate';


export interface ExchangeDay { 
    date: string;
    rates: Array<ExchangeRate>;
}

